### ISSUE TITLE
Writing to a word address

### ISSUE THREAD

**Issue by diginfo** [hwstar/Buspirate-python3-i2c#2]
Hi;

Firstly, thanks for translating this for use on python3, I am hoping you can help.

I am trying to set bytes to a **word address** however I am getting a:

`ValueError: bytes must be in range(0, 256)`

I have googled this and understand that chr() in python2 only accepts byte values, however in python3 it should accept larger (word) values.

Here's the code:

    def set_byte(i2c,i2caddr, addr, value):
        """ Write one byte to address addr """
        i2c.send_start_bit();
        stat = i2c.bulk_trans(3, [i2caddr, addr, value]);
        i2c.send_stop_bit();

    set_byte(i2c,i2caddr, 0xff5a, 0x4f)

And here's the error:

    Traceback (most recent call last):
      File "/Volumes/Data/uPython/busPirate/pac.py", line 176, in <module>
        reset()
      File "/Volumes/Data/uPython/busPirate/pac.py", line 109, in reset
        set_byte(i2c,i2caddr, 0xff5a, 0x4f)
      File "/Volumes/Data/uPython/busPirate/pac.py", line 35, in set_byte
        stat = i2c.bulk_trans(3, [i2caddr, addr, value]);
      File "/Volumes/Data/uPython/busPirate/pyBusPirateLite/BitBang.py", line 208, in bulk_trans
        self.port.write(bytes([byte_string[i]]))
    ValueError: bytes must be in range(0, 256)

Any idea on the solution ?

**Comment by hwstar** [comment]
I think you'll need to convert words to bytes using struct.pack or something similar:

https://docs.python.org/3/library/struct.html

The problem is that the serial port write method only accepts bytes which have a range of 0-255.

Steve
